### YamlMime:ManagedReference
items:
- uid: Prowl.Editor.Projects.Settings.AssetExportMode
  commentId: T:Prowl.Editor.Projects.Settings.AssetExportMode
  id: AssetExportMode
  parent: Prowl.Editor.Projects.Settings
  children:
  - Prowl.Editor.Projects.Settings.AssetExportMode.AllAssets
  - Prowl.Editor.Projects.Settings.AssetExportMode.DependenciesOnly
  langs:
  - csharp
  - vb
  name: AssetExportMode
  nameWithType: AssetExportMode
  fullName: Prowl.Editor.Projects.Settings.AssetExportMode
  type: Enum
  source:
    remote:
      path: Prowl.Editor/Projects/Settings/BuildSettings.cs
      branch: main
      repo: https://github.com/ProwlEngine/Prowl.git
    id: AssetExportMode
    path: ../Prowl/Prowl.Editor/Projects/Settings/BuildSettings.cs
    startLine: 18
  assemblies:
  - Prowl.Editor
  namespace: Prowl.Editor.Projects.Settings
  syntax:
    content: public enum AssetExportMode
    content.vb: Public Enum AssetExportMode
  extensionMethods:
  - System.Object.Prowl.Runtime.RuntimeUtils.GetSerializableFields
- uid: Prowl.Editor.Projects.Settings.AssetExportMode.AllAssets
  commentId: F:Prowl.Editor.Projects.Settings.AssetExportMode.AllAssets
  id: AllAssets
  parent: Prowl.Editor.Projects.Settings.AssetExportMode
  langs:
  - csharp
  - vb
  name: AllAssets
  nameWithType: AssetExportMode.AllAssets
  fullName: Prowl.Editor.Projects.Settings.AssetExportMode.AllAssets
  type: Field
  source:
    remote:
      path: Prowl.Editor/Projects/Settings/BuildSettings.cs
      branch: main
      repo: https://github.com/ProwlEngine/Prowl.git
    id: AllAssets
    path: ../Prowl/Prowl.Editor/Projects/Settings/BuildSettings.cs
    startLine: 18
  assemblies:
  - Prowl.Editor
  namespace: Prowl.Editor.Projects.Settings
  syntax:
    content: AllAssets = 0
    return:
      type: Prowl.Editor.Projects.Settings.AssetExportMode
- uid: Prowl.Editor.Projects.Settings.AssetExportMode.DependenciesOnly
  commentId: F:Prowl.Editor.Projects.Settings.AssetExportMode.DependenciesOnly
  id: DependenciesOnly
  parent: Prowl.Editor.Projects.Settings.AssetExportMode
  langs:
  - csharp
  - vb
  name: DependenciesOnly
  nameWithType: AssetExportMode.DependenciesOnly
  fullName: Prowl.Editor.Projects.Settings.AssetExportMode.DependenciesOnly
  type: Field
  source:
    remote:
      path: Prowl.Editor/Projects/Settings/BuildSettings.cs
      branch: main
      repo: https://github.com/ProwlEngine/Prowl.git
    id: DependenciesOnly
    path: ../Prowl/Prowl.Editor/Projects/Settings/BuildSettings.cs
    startLine: 18
  assemblies:
  - Prowl.Editor
  namespace: Prowl.Editor.Projects.Settings
  syntax:
    content: DependenciesOnly = 1
    return:
      type: Prowl.Editor.Projects.Settings.AssetExportMode
references:
- uid: Prowl.Editor.Projects.Settings
  commentId: N:Prowl.Editor.Projects.Settings
  name: Prowl.Editor.Projects.Settings
  nameWithType: Prowl.Editor.Projects.Settings
  fullName: Prowl.Editor.Projects.Settings
  spec.csharp:
  - uid: Prowl
    name: Prowl
  - name: .
  - uid: Prowl.Editor
    name: Editor
  - name: .
  - uid: Prowl.Editor.Projects
    name: Projects
  - name: .
  - uid: Prowl.Editor.Projects.Settings
    name: Settings
  spec.vb:
  - uid: Prowl
    name: Prowl
  - name: .
  - uid: Prowl.Editor
    name: Editor
  - name: .
  - uid: Prowl.Editor.Projects
    name: Projects
  - name: .
  - uid: Prowl.Editor.Projects.Settings
    name: Settings
- uid: System.Object.Prowl.Runtime.RuntimeUtils.GetSerializableFields
  commentId: M:Prowl.Runtime.RuntimeUtils.GetSerializableFields(System.Object)
  parent: Prowl.Runtime.RuntimeUtils
  definition: Prowl.Runtime.RuntimeUtils.GetSerializableFields(System.Object)
  href: Prowl.Runtime.RuntimeUtils.html#Prowl_Runtime_RuntimeUtils_GetSerializableFields_System_Object_
  name: GetSerializableFields(object)
  nameWithType: RuntimeUtils.GetSerializableFields(object)
  fullName: Prowl.Runtime.RuntimeUtils.GetSerializableFields(object)
  nameWithType.vb: RuntimeUtils.GetSerializableFields(Object)
  fullName.vb: Prowl.Runtime.RuntimeUtils.GetSerializableFields(Object)
  name.vb: GetSerializableFields(Object)
  spec.csharp:
  - uid: Prowl.Runtime.RuntimeUtils.GetSerializableFields(System.Object)
    name: GetSerializableFields
    href: Prowl.Runtime.RuntimeUtils.html#Prowl_Runtime_RuntimeUtils_GetSerializableFields_System_Object_
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: Prowl.Runtime.RuntimeUtils.GetSerializableFields(System.Object)
    name: GetSerializableFields
    href: Prowl.Runtime.RuntimeUtils.html#Prowl_Runtime_RuntimeUtils_GetSerializableFields_System_Object_
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: Prowl.Runtime.RuntimeUtils.GetSerializableFields(System.Object)
  commentId: M:Prowl.Runtime.RuntimeUtils.GetSerializableFields(System.Object)
  isExternal: true
  href: Prowl.Runtime.RuntimeUtils.html#Prowl_Runtime_RuntimeUtils_GetSerializableFields_System_Object_
  name: GetSerializableFields(object)
  nameWithType: RuntimeUtils.GetSerializableFields(object)
  fullName: Prowl.Runtime.RuntimeUtils.GetSerializableFields(object)
  nameWithType.vb: RuntimeUtils.GetSerializableFields(Object)
  fullName.vb: Prowl.Runtime.RuntimeUtils.GetSerializableFields(Object)
  name.vb: GetSerializableFields(Object)
  spec.csharp:
  - uid: Prowl.Runtime.RuntimeUtils.GetSerializableFields(System.Object)
    name: GetSerializableFields
    href: Prowl.Runtime.RuntimeUtils.html#Prowl_Runtime_RuntimeUtils_GetSerializableFields_System_Object_
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: Prowl.Runtime.RuntimeUtils.GetSerializableFields(System.Object)
    name: GetSerializableFields
    href: Prowl.Runtime.RuntimeUtils.html#Prowl_Runtime_RuntimeUtils_GetSerializableFields_System_Object_
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: Prowl.Runtime.RuntimeUtils
  commentId: T:Prowl.Runtime.RuntimeUtils
  parent: Prowl.Runtime
  href: Prowl.Runtime.RuntimeUtils.html
  name: RuntimeUtils
  nameWithType: RuntimeUtils
  fullName: Prowl.Runtime.RuntimeUtils
- uid: Prowl.Runtime
  commentId: N:Prowl.Runtime
  name: Prowl.Runtime
  nameWithType: Prowl.Runtime
  fullName: Prowl.Runtime
  spec.csharp:
  - uid: Prowl
    name: Prowl
  - name: .
  - uid: Prowl.Runtime
    name: Runtime
  spec.vb:
  - uid: Prowl
    name: Prowl
  - name: .
  - uid: Prowl.Runtime
    name: Runtime
- uid: Prowl.Editor.Projects.Settings.AssetExportMode
  commentId: T:Prowl.Editor.Projects.Settings.AssetExportMode
  parent: Prowl.Editor.Projects.Settings
  href: Prowl.Editor.Projects.Settings.AssetExportMode.html
  name: AssetExportMode
  nameWithType: AssetExportMode
  fullName: Prowl.Editor.Projects.Settings.AssetExportMode
