### YamlMime:ManagedReference
items:
- uid: Prowl.Editor.GUI.Panels.BuildSettingsPanel.BuildStatusReport.BuildStatusReportType
  commentId: T:Prowl.Editor.GUI.Panels.BuildSettingsPanel.BuildStatusReport.BuildStatusReportType
  id: BuildSettingsPanel.BuildStatusReport.BuildStatusReportType
  parent: Prowl.Editor.GUI.Panels
  children:
  - Prowl.Editor.GUI.Panels.BuildSettingsPanel.BuildStatusReport.BuildStatusReportType.Info
  - Prowl.Editor.GUI.Panels.BuildSettingsPanel.BuildStatusReport.BuildStatusReportType.Progress
  langs:
  - csharp
  - vb
  name: BuildSettingsPanel.BuildStatusReport.BuildStatusReportType
  nameWithType: BuildSettingsPanel.BuildStatusReport.BuildStatusReportType
  fullName: Prowl.Editor.GUI.Panels.BuildSettingsPanel.BuildStatusReport.BuildStatusReportType
  type: Enum
  source:
    remote:
      path: Prowl.Editor/GUI/Panels/BuildSettingsPanel.cs
      branch: main
      repo: https://github.com/ProwlEngine/Prowl.git
    id: BuildStatusReportType
    path: ../Prowl/Prowl.Editor/GUI/Panels/BuildSettingsPanel.cs
    startLine: 37
  assemblies:
  - Prowl.Editor
  namespace: Prowl.Editor.GUI.Panels
  syntax:
    content: public enum BuildSettingsPanel.BuildStatusReport.BuildStatusReportType
    content.vb: Public Enum BuildSettingsPanel.BuildStatusReport.BuildStatusReportType
  extensionMethods:
  - System.Object.Prowl.Runtime.RuntimeUtils.GetSerializableFields
- uid: Prowl.Editor.GUI.Panels.BuildSettingsPanel.BuildStatusReport.BuildStatusReportType.Info
  commentId: F:Prowl.Editor.GUI.Panels.BuildSettingsPanel.BuildStatusReport.BuildStatusReportType.Info
  id: Info
  parent: Prowl.Editor.GUI.Panels.BuildSettingsPanel.BuildStatusReport.BuildStatusReportType
  langs:
  - csharp
  - vb
  name: Info
  nameWithType: BuildSettingsPanel.BuildStatusReport.BuildStatusReportType.Info
  fullName: Prowl.Editor.GUI.Panels.BuildSettingsPanel.BuildStatusReport.BuildStatusReportType.Info
  type: Field
  source:
    remote:
      path: Prowl.Editor/GUI/Panels/BuildSettingsPanel.cs
      branch: main
      repo: https://github.com/ProwlEngine/Prowl.git
    id: Info
    path: ../Prowl/Prowl.Editor/GUI/Panels/BuildSettingsPanel.cs
    startLine: 39
  assemblies:
  - Prowl.Editor
  namespace: Prowl.Editor.GUI.Panels
  syntax:
    content: Info = 0
    return:
      type: Prowl.Editor.GUI.Panels.BuildSettingsPanel.BuildStatusReport.BuildStatusReportType
- uid: Prowl.Editor.GUI.Panels.BuildSettingsPanel.BuildStatusReport.BuildStatusReportType.Progress
  commentId: F:Prowl.Editor.GUI.Panels.BuildSettingsPanel.BuildStatusReport.BuildStatusReportType.Progress
  id: Progress
  parent: Prowl.Editor.GUI.Panels.BuildSettingsPanel.BuildStatusReport.BuildStatusReportType
  langs:
  - csharp
  - vb
  name: Progress
  nameWithType: BuildSettingsPanel.BuildStatusReport.BuildStatusReportType.Progress
  fullName: Prowl.Editor.GUI.Panels.BuildSettingsPanel.BuildStatusReport.BuildStatusReportType.Progress
  type: Field
  source:
    remote:
      path: Prowl.Editor/GUI/Panels/BuildSettingsPanel.cs
      branch: main
      repo: https://github.com/ProwlEngine/Prowl.git
    id: Progress
    path: ../Prowl/Prowl.Editor/GUI/Panels/BuildSettingsPanel.cs
    startLine: 40
  assemblies:
  - Prowl.Editor
  namespace: Prowl.Editor.GUI.Panels
  syntax:
    content: Progress = 1
    return:
      type: Prowl.Editor.GUI.Panels.BuildSettingsPanel.BuildStatusReport.BuildStatusReportType
references:
- uid: Prowl.Editor.GUI.Panels
  commentId: N:Prowl.Editor.GUI.Panels
  name: Prowl.Editor.GUI.Panels
  nameWithType: Prowl.Editor.GUI.Panels
  fullName: Prowl.Editor.GUI.Panels
  spec.csharp:
  - uid: Prowl
    name: Prowl
  - name: .
  - uid: Prowl.Editor
    name: Editor
  - name: .
  - uid: Prowl.Editor.GUI
    name: GUI
  - name: .
  - uid: Prowl.Editor.GUI.Panels
    name: Panels
  spec.vb:
  - uid: Prowl
    name: Prowl
  - name: .
  - uid: Prowl.Editor
    name: Editor
  - name: .
  - uid: Prowl.Editor.GUI
    name: GUI
  - name: .
  - uid: Prowl.Editor.GUI.Panels
    name: Panels
- uid: System.Object.Prowl.Runtime.RuntimeUtils.GetSerializableFields
  commentId: M:Prowl.Runtime.RuntimeUtils.GetSerializableFields(System.Object)
  parent: Prowl.Runtime.RuntimeUtils
  definition: Prowl.Runtime.RuntimeUtils.GetSerializableFields(System.Object)
  href: Prowl.Runtime.RuntimeUtils.html#Prowl_Runtime_RuntimeUtils_GetSerializableFields_System_Object_
  name: GetSerializableFields(object)
  nameWithType: RuntimeUtils.GetSerializableFields(object)
  fullName: Prowl.Runtime.RuntimeUtils.GetSerializableFields(object)
  nameWithType.vb: RuntimeUtils.GetSerializableFields(Object)
  fullName.vb: Prowl.Runtime.RuntimeUtils.GetSerializableFields(Object)
  name.vb: GetSerializableFields(Object)
  spec.csharp:
  - uid: Prowl.Runtime.RuntimeUtils.GetSerializableFields(System.Object)
    name: GetSerializableFields
    href: Prowl.Runtime.RuntimeUtils.html#Prowl_Runtime_RuntimeUtils_GetSerializableFields_System_Object_
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: Prowl.Runtime.RuntimeUtils.GetSerializableFields(System.Object)
    name: GetSerializableFields
    href: Prowl.Runtime.RuntimeUtils.html#Prowl_Runtime_RuntimeUtils_GetSerializableFields_System_Object_
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: Prowl.Runtime.RuntimeUtils.GetSerializableFields(System.Object)
  commentId: M:Prowl.Runtime.RuntimeUtils.GetSerializableFields(System.Object)
  isExternal: true
  href: Prowl.Runtime.RuntimeUtils.html#Prowl_Runtime_RuntimeUtils_GetSerializableFields_System_Object_
  name: GetSerializableFields(object)
  nameWithType: RuntimeUtils.GetSerializableFields(object)
  fullName: Prowl.Runtime.RuntimeUtils.GetSerializableFields(object)
  nameWithType.vb: RuntimeUtils.GetSerializableFields(Object)
  fullName.vb: Prowl.Runtime.RuntimeUtils.GetSerializableFields(Object)
  name.vb: GetSerializableFields(Object)
  spec.csharp:
  - uid: Prowl.Runtime.RuntimeUtils.GetSerializableFields(System.Object)
    name: GetSerializableFields
    href: Prowl.Runtime.RuntimeUtils.html#Prowl_Runtime_RuntimeUtils_GetSerializableFields_System_Object_
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: Prowl.Runtime.RuntimeUtils.GetSerializableFields(System.Object)
    name: GetSerializableFields
    href: Prowl.Runtime.RuntimeUtils.html#Prowl_Runtime_RuntimeUtils_GetSerializableFields_System_Object_
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: Prowl.Runtime.RuntimeUtils
  commentId: T:Prowl.Runtime.RuntimeUtils
  parent: Prowl.Runtime
  href: Prowl.Runtime.RuntimeUtils.html
  name: RuntimeUtils
  nameWithType: RuntimeUtils
  fullName: Prowl.Runtime.RuntimeUtils
- uid: Prowl.Runtime
  commentId: N:Prowl.Runtime
  name: Prowl.Runtime
  nameWithType: Prowl.Runtime
  fullName: Prowl.Runtime
  spec.csharp:
  - uid: Prowl
    name: Prowl
  - name: .
  - uid: Prowl.Runtime
    name: Runtime
  spec.vb:
  - uid: Prowl
    name: Prowl
  - name: .
  - uid: Prowl.Runtime
    name: Runtime
- uid: Prowl.Editor.GUI.Panels.BuildSettingsPanel.BuildStatusReport.BuildStatusReportType
  commentId: T:Prowl.Editor.GUI.Panels.BuildSettingsPanel.BuildStatusReport.BuildStatusReportType
  parent: Prowl.Editor.GUI.Panels
  href: Prowl.Editor.GUI.Panels.BuildSettingsPanel.html
  name: BuildSettingsPanel.BuildStatusReport.BuildStatusReportType
  nameWithType: BuildSettingsPanel.BuildStatusReport.BuildStatusReportType
  fullName: Prowl.Editor.GUI.Panels.BuildSettingsPanel.BuildStatusReport.BuildStatusReportType
  spec.csharp:
  - uid: Prowl.Editor.GUI.Panels.BuildSettingsPanel
    name: BuildSettingsPanel
    href: Prowl.Editor.GUI.Panels.BuildSettingsPanel.html
  - name: .
  - uid: Prowl.Editor.GUI.Panels.BuildSettingsPanel.BuildStatusReport
    name: BuildStatusReport
    href: Prowl.Editor.GUI.Panels.BuildSettingsPanel.BuildStatusReport.html
  - name: .
  - uid: Prowl.Editor.GUI.Panels.BuildSettingsPanel.BuildStatusReport.BuildStatusReportType
    name: BuildStatusReportType
    href: Prowl.Editor.GUI.Panels.BuildSettingsPanel.BuildStatusReport.BuildStatusReportType.html
  spec.vb:
  - uid: Prowl.Editor.GUI.Panels.BuildSettingsPanel
    name: BuildSettingsPanel
    href: Prowl.Editor.GUI.Panels.BuildSettingsPanel.html
  - name: .
  - uid: Prowl.Editor.GUI.Panels.BuildSettingsPanel.BuildStatusReport
    name: BuildStatusReport
    href: Prowl.Editor.GUI.Panels.BuildSettingsPanel.BuildStatusReport.html
  - name: .
  - uid: Prowl.Editor.GUI.Panels.BuildSettingsPanel.BuildStatusReport.BuildStatusReportType
    name: BuildStatusReportType
    href: Prowl.Editor.GUI.Panels.BuildSettingsPanel.BuildStatusReport.BuildStatusReportType.html
