### YamlMime:ManagedReference
items:
- uid: Prowl.Editor.Projects.Settings
  commentId: N:Prowl.Editor.Projects.Settings
  id: Prowl.Editor.Projects.Settings
  children:
  - Prowl.Editor.Projects.Settings.AssetExportMode
  - Prowl.Editor.Projects.Settings.AssetSettings
  - Prowl.Editor.Projects.Settings.AudioSettings
  - Prowl.Editor.Projects.Settings.BuildConfiguration
  - Prowl.Editor.Projects.Settings.BuildSettings
  - Prowl.Editor.Projects.Settings.BuildTarget
  - Prowl.Editor.Projects.Settings.GeneralSettings
  - Prowl.Editor.Projects.Settings.NavigationSettings
  - Prowl.Editor.Projects.Settings.PhysicsSettings
  - Prowl.Editor.Projects.Settings.ProjectSettingsAttribute
  - Prowl.Editor.Projects.Settings.ProjectSettingsBase
  - Prowl.Editor.Projects.Settings.ProjectsEditorSettings
  - Prowl.Editor.Projects.Settings.SceneBuildEntry
  - Prowl.Editor.Projects.Settings.SerializerType
  - Prowl.Editor.Projects.Settings.TagsAndLayersSettings
  - Prowl.Editor.Projects.Settings.TimeSettings
  - Prowl.Editor.Projects.Settings.XRSettings
  langs:
  - csharp
  - vb
  name: Prowl.Editor.Projects.Settings
  nameWithType: Prowl.Editor.Projects.Settings
  fullName: Prowl.Editor.Projects.Settings
  type: Namespace
  assemblies:
  - Prowl.Editor
references:
- uid: Prowl.Editor.Projects.Settings.AssetSettings
  commentId: T:Prowl.Editor.Projects.Settings.AssetSettings
  href: Prowl.Editor.Projects.Settings.AssetSettings.html
  name: AssetSettings
  nameWithType: AssetSettings
  fullName: Prowl.Editor.Projects.Settings.AssetSettings
- uid: Prowl.Editor.Projects.Settings.AudioSettings
  commentId: T:Prowl.Editor.Projects.Settings.AudioSettings
  href: Prowl.Editor.Projects.Settings.AudioSettings.html
  name: AudioSettings
  nameWithType: AudioSettings
  fullName: Prowl.Editor.Projects.Settings.AudioSettings
- uid: Prowl.Editor.Projects.Settings.BuildTarget
  commentId: T:Prowl.Editor.Projects.Settings.BuildTarget
  parent: Prowl.Editor.Projects.Settings
  href: Prowl.Editor.Projects.Settings.BuildTarget.html
  name: BuildTarget
  nameWithType: BuildTarget
  fullName: Prowl.Editor.Projects.Settings.BuildTarget
- uid: Prowl.Editor.Projects.Settings.BuildConfiguration
  commentId: T:Prowl.Editor.Projects.Settings.BuildConfiguration
  parent: Prowl.Editor.Projects.Settings
  href: Prowl.Editor.Projects.Settings.BuildConfiguration.html
  name: BuildConfiguration
  nameWithType: BuildConfiguration
  fullName: Prowl.Editor.Projects.Settings.BuildConfiguration
- uid: Prowl.Editor.Projects.Settings.AssetExportMode
  commentId: T:Prowl.Editor.Projects.Settings.AssetExportMode
  parent: Prowl.Editor.Projects.Settings
  href: Prowl.Editor.Projects.Settings.AssetExportMode.html
  name: AssetExportMode
  nameWithType: AssetExportMode
  fullName: Prowl.Editor.Projects.Settings.AssetExportMode
- uid: Prowl.Editor.Projects.Settings.SceneBuildEntry
  commentId: T:Prowl.Editor.Projects.Settings.SceneBuildEntry
  href: Prowl.Editor.Projects.Settings.SceneBuildEntry.html
  name: SceneBuildEntry
  nameWithType: SceneBuildEntry
  fullName: Prowl.Editor.Projects.Settings.SceneBuildEntry
- uid: Prowl.Editor.Projects.Settings.BuildSettings
  commentId: T:Prowl.Editor.Projects.Settings.BuildSettings
  parent: Prowl.Editor.Projects.Settings
  href: Prowl.Editor.Projects.Settings.BuildSettings.html
  name: BuildSettings
  nameWithType: BuildSettings
  fullName: Prowl.Editor.Projects.Settings.BuildSettings
- uid: Prowl.Editor.Projects.Settings.GeneralSettings
  commentId: T:Prowl.Editor.Projects.Settings.GeneralSettings
  href: Prowl.Editor.Projects.Settings.GeneralSettings.html
  name: GeneralSettings
  nameWithType: GeneralSettings
  fullName: Prowl.Editor.Projects.Settings.GeneralSettings
- uid: Prowl.Editor.Projects.Settings.NavigationSettings
  commentId: T:Prowl.Editor.Projects.Settings.NavigationSettings
  href: Prowl.Editor.Projects.Settings.NavigationSettings.html
  name: NavigationSettings
  nameWithType: NavigationSettings
  fullName: Prowl.Editor.Projects.Settings.NavigationSettings
- uid: Prowl.Editor.Projects.Settings.PhysicsSettings
  commentId: T:Prowl.Editor.Projects.Settings.PhysicsSettings
  href: Prowl.Editor.Projects.Settings.PhysicsSettings.html
  name: PhysicsSettings
  nameWithType: PhysicsSettings
  fullName: Prowl.Editor.Projects.Settings.PhysicsSettings
- uid: Prowl.Editor.Projects.Settings.ProjectsEditorSettings
  commentId: T:Prowl.Editor.Projects.Settings.ProjectsEditorSettings
  href: Prowl.Editor.Projects.Settings.ProjectsEditorSettings.html
  name: ProjectsEditorSettings
  nameWithType: ProjectsEditorSettings
  fullName: Prowl.Editor.Projects.Settings.ProjectsEditorSettings
- uid: Prowl.Editor.Projects.Settings.ProjectSettingsAttribute
  commentId: T:Prowl.Editor.Projects.Settings.ProjectSettingsAttribute
  parent: Prowl.Editor.Projects.Settings
  href: Prowl.Editor.Projects.Settings.ProjectSettingsAttribute.html
  name: ProjectSettingsAttribute
  nameWithType: ProjectSettingsAttribute
  fullName: Prowl.Editor.Projects.Settings.ProjectSettingsAttribute
- uid: Prowl.Editor.Projects.Settings.SerializerType
  commentId: T:Prowl.Editor.Projects.Settings.SerializerType
  parent: Prowl.Editor.Projects.Settings
  href: Prowl.Editor.Projects.Settings.SerializerType.html
  name: SerializerType
  nameWithType: SerializerType
  fullName: Prowl.Editor.Projects.Settings.SerializerType
- uid: Prowl.Editor.Projects.Settings.ProjectSettingsBase
  commentId: T:Prowl.Editor.Projects.Settings.ProjectSettingsBase
  parent: Prowl.Editor.Projects.Settings
  href: Prowl.Editor.Projects.Settings.ProjectSettingsBase.html
  name: ProjectSettingsBase
  nameWithType: ProjectSettingsBase
  fullName: Prowl.Editor.Projects.Settings.ProjectSettingsBase
- uid: Prowl.Editor.Projects.Settings.TagsAndLayersSettings
  commentId: T:Prowl.Editor.Projects.Settings.TagsAndLayersSettings
  href: Prowl.Editor.Projects.Settings.TagsAndLayersSettings.html
  name: TagsAndLayersSettings
  nameWithType: TagsAndLayersSettings
  fullName: Prowl.Editor.Projects.Settings.TagsAndLayersSettings
- uid: Prowl.Editor.Projects.Settings.TimeSettings
  commentId: T:Prowl.Editor.Projects.Settings.TimeSettings
  href: Prowl.Editor.Projects.Settings.TimeSettings.html
  name: TimeSettings
  nameWithType: TimeSettings
  fullName: Prowl.Editor.Projects.Settings.TimeSettings
- uid: Prowl.Editor.Projects.Settings.XRSettings
  commentId: T:Prowl.Editor.Projects.Settings.XRSettings
  href: Prowl.Editor.Projects.Settings.XRSettings.html
  name: XRSettings
  nameWithType: XRSettings
  fullName: Prowl.Editor.Projects.Settings.XRSettings
- uid: Prowl.Editor.Projects.Settings
  commentId: N:Prowl.Editor.Projects.Settings
  name: Prowl.Editor.Projects.Settings
  nameWithType: Prowl.Editor.Projects.Settings
  fullName: Prowl.Editor.Projects.Settings
  spec.csharp:
  - uid: Prowl
    name: Prowl
  - name: .
  - uid: Prowl.Editor
    name: Editor
  - name: .
  - uid: Prowl.Editor.Projects
    name: Projects
  - name: .
  - uid: Prowl.Editor.Projects.Settings
    name: Settings
  spec.vb:
  - uid: Prowl
    name: Prowl
  - name: .
  - uid: Prowl.Editor
    name: Editor
  - name: .
  - uid: Prowl.Editor.Projects
    name: Projects
  - name: .
  - uid: Prowl.Editor.Projects.Settings
    name: Settings
