### YamlMime:ManagedReference
items:
- uid: Prowl.Editor.GUI.Panels.BuildSettingsPanel.BuildPipelineInfo
  commentId: T:Prowl.Editor.GUI.Panels.BuildSettingsPanel.BuildPipelineInfo
  id: BuildSettingsPanel.BuildPipelineInfo
  parent: Prowl.Editor.GUI.Panels
  children:
  - Prowl.Editor.GUI.Panels.BuildSettingsPanel.BuildPipelineInfo.BuildPipelineType
  - Prowl.Editor.GUI.Panels.BuildSettingsPanel.BuildPipelineInfo.Icon
  - Prowl.Editor.GUI.Panels.BuildSettingsPanel.BuildPipelineInfo.Name
  langs:
  - csharp
  - vb
  name: BuildSettingsPanel.BuildPipelineInfo
  nameWithType: BuildSettingsPanel.BuildPipelineInfo
  fullName: Prowl.Editor.GUI.Panels.BuildSettingsPanel.BuildPipelineInfo
  type: Struct
  source:
    remote:
      path: Prowl.Editor/GUI/Panels/BuildSettingsPanel.cs
      branch: main
      repo: https://github.com/ProwlEngine/Prowl.git
    id: BuildPipelineInfo
    path: ../Prowl/Prowl.Editor/GUI/Panels/BuildSettingsPanel.cs
    startLine: 49
  assemblies:
  - Prowl.Editor
  namespace: Prowl.Editor.GUI.Panels
  syntax:
    content: public struct BuildSettingsPanel.BuildPipelineInfo
    content.vb: Public Structure BuildSettingsPanel.BuildPipelineInfo
  inheritedMembers:
  - System.ValueType.Equals(System.Object)
  - System.ValueType.GetHashCode
  - System.ValueType.ToString
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetType
  - System.Object.ReferenceEquals(System.Object,System.Object)
  extensionMethods:
  - System.Object.Prowl.Runtime.RuntimeUtils.GetSerializableFields
- uid: Prowl.Editor.GUI.Panels.BuildSettingsPanel.BuildPipelineInfo.Name
  commentId: F:Prowl.Editor.GUI.Panels.BuildSettingsPanel.BuildPipelineInfo.Name
  id: Name
  parent: Prowl.Editor.GUI.Panels.BuildSettingsPanel.BuildPipelineInfo
  langs:
  - csharp
  - vb
  name: Name
  nameWithType: BuildSettingsPanel.BuildPipelineInfo.Name
  fullName: Prowl.Editor.GUI.Panels.BuildSettingsPanel.BuildPipelineInfo.Name
  type: Field
  source:
    remote:
      path: Prowl.Editor/GUI/Panels/BuildSettingsPanel.cs
      branch: main
      repo: https://github.com/ProwlEngine/Prowl.git
    id: Name
    path: ../Prowl/Prowl.Editor/GUI/Panels/BuildSettingsPanel.cs
    startLine: 51
  assemblies:
  - Prowl.Editor
  namespace: Prowl.Editor.GUI.Panels
  syntax:
    content: public string Name
    return:
      type: System.String
    content.vb: Public Name As String
- uid: Prowl.Editor.GUI.Panels.BuildSettingsPanel.BuildPipelineInfo.Icon
  commentId: F:Prowl.Editor.GUI.Panels.BuildSettingsPanel.BuildPipelineInfo.Icon
  id: Icon
  parent: Prowl.Editor.GUI.Panels.BuildSettingsPanel.BuildPipelineInfo
  langs:
  - csharp
  - vb
  name: Icon
  nameWithType: BuildSettingsPanel.BuildPipelineInfo.Icon
  fullName: Prowl.Editor.GUI.Panels.BuildSettingsPanel.BuildPipelineInfo.Icon
  type: Field
  source:
    remote:
      path: Prowl.Editor/GUI/Panels/BuildSettingsPanel.cs
      branch: main
      repo: https://github.com/ProwlEngine/Prowl.git
    id: Icon
    path: ../Prowl/Prowl.Editor/GUI/Panels/BuildSettingsPanel.cs
    startLine: 52
  assemblies:
  - Prowl.Editor
  namespace: Prowl.Editor.GUI.Panels
  syntax:
    content: public string Icon
    return:
      type: System.String
    content.vb: Public Icon As String
- uid: Prowl.Editor.GUI.Panels.BuildSettingsPanel.BuildPipelineInfo.BuildPipelineType
  commentId: F:Prowl.Editor.GUI.Panels.BuildSettingsPanel.BuildPipelineInfo.BuildPipelineType
  id: BuildPipelineType
  parent: Prowl.Editor.GUI.Panels.BuildSettingsPanel.BuildPipelineInfo
  langs:
  - csharp
  - vb
  name: BuildPipelineType
  nameWithType: BuildSettingsPanel.BuildPipelineInfo.BuildPipelineType
  fullName: Prowl.Editor.GUI.Panels.BuildSettingsPanel.BuildPipelineInfo.BuildPipelineType
  type: Field
  source:
    remote:
      path: Prowl.Editor/GUI/Panels/BuildSettingsPanel.cs
      branch: main
      repo: https://github.com/ProwlEngine/Prowl.git
    id: BuildPipelineType
    path: ../Prowl/Prowl.Editor/GUI/Panels/BuildSettingsPanel.cs
    startLine: 53
  assemblies:
  - Prowl.Editor
  namespace: Prowl.Editor.GUI.Panels
  syntax:
    content: public Type BuildPipelineType
    return:
      type: System.Type
    content.vb: Public BuildPipelineType As Type
references:
- uid: Prowl.Editor.GUI.Panels
  commentId: N:Prowl.Editor.GUI.Panels
  name: Prowl.Editor.GUI.Panels
  nameWithType: Prowl.Editor.GUI.Panels
  fullName: Prowl.Editor.GUI.Panels
  spec.csharp:
  - uid: Prowl
    name: Prowl
  - name: .
  - uid: Prowl.Editor
    name: Editor
  - name: .
  - uid: Prowl.Editor.GUI
    name: GUI
  - name: .
  - uid: Prowl.Editor.GUI.Panels
    name: Panels
  spec.vb:
  - uid: Prowl
    name: Prowl
  - name: .
  - uid: Prowl.Editor
    name: Editor
  - name: .
  - uid: Prowl.Editor.GUI
    name: GUI
  - name: .
  - uid: Prowl.Editor.GUI.Panels
    name: Panels
- uid: System.ValueType.Equals(System.Object)
  commentId: M:System.ValueType.Equals(System.Object)
  parent: System.ValueType
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.valuetype.equals
  name: Equals(object)
  nameWithType: ValueType.Equals(object)
  fullName: System.ValueType.Equals(object)
  nameWithType.vb: ValueType.Equals(Object)
  fullName.vb: System.ValueType.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.ValueType.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.valuetype.equals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.ValueType.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.valuetype.equals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.ValueType.GetHashCode
  commentId: M:System.ValueType.GetHashCode
  parent: System.ValueType
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.valuetype.gethashcode
  name: GetHashCode()
  nameWithType: ValueType.GetHashCode()
  fullName: System.ValueType.GetHashCode()
  spec.csharp:
  - uid: System.ValueType.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.valuetype.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.ValueType.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.valuetype.gethashcode
  - name: (
  - name: )
- uid: System.ValueType.ToString
  commentId: M:System.ValueType.ToString
  parent: System.ValueType
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.valuetype.tostring
  name: ToString()
  nameWithType: ValueType.ToString()
  fullName: System.ValueType.ToString()
  spec.csharp:
  - uid: System.ValueType.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.valuetype.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.ValueType.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.valuetype.tostring
  - name: (
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.Prowl.Runtime.RuntimeUtils.GetSerializableFields
  commentId: M:Prowl.Runtime.RuntimeUtils.GetSerializableFields(System.Object)
  parent: Prowl.Runtime.RuntimeUtils
  definition: Prowl.Runtime.RuntimeUtils.GetSerializableFields(System.Object)
  href: Prowl.Runtime.RuntimeUtils.html#Prowl_Runtime_RuntimeUtils_GetSerializableFields_System_Object_
  name: GetSerializableFields(object)
  nameWithType: RuntimeUtils.GetSerializableFields(object)
  fullName: Prowl.Runtime.RuntimeUtils.GetSerializableFields(object)
  nameWithType.vb: RuntimeUtils.GetSerializableFields(Object)
  fullName.vb: Prowl.Runtime.RuntimeUtils.GetSerializableFields(Object)
  name.vb: GetSerializableFields(Object)
  spec.csharp:
  - uid: Prowl.Runtime.RuntimeUtils.GetSerializableFields(System.Object)
    name: GetSerializableFields
    href: Prowl.Runtime.RuntimeUtils.html#Prowl_Runtime_RuntimeUtils_GetSerializableFields_System_Object_
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: Prowl.Runtime.RuntimeUtils.GetSerializableFields(System.Object)
    name: GetSerializableFields
    href: Prowl.Runtime.RuntimeUtils.html#Prowl_Runtime_RuntimeUtils_GetSerializableFields_System_Object_
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.ValueType
  commentId: T:System.ValueType
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.valuetype
  name: ValueType
  nameWithType: ValueType
  fullName: System.ValueType
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: Prowl.Runtime.RuntimeUtils.GetSerializableFields(System.Object)
  commentId: M:Prowl.Runtime.RuntimeUtils.GetSerializableFields(System.Object)
  isExternal: true
  href: Prowl.Runtime.RuntimeUtils.html#Prowl_Runtime_RuntimeUtils_GetSerializableFields_System_Object_
  name: GetSerializableFields(object)
  nameWithType: RuntimeUtils.GetSerializableFields(object)
  fullName: Prowl.Runtime.RuntimeUtils.GetSerializableFields(object)
  nameWithType.vb: RuntimeUtils.GetSerializableFields(Object)
  fullName.vb: Prowl.Runtime.RuntimeUtils.GetSerializableFields(Object)
  name.vb: GetSerializableFields(Object)
  spec.csharp:
  - uid: Prowl.Runtime.RuntimeUtils.GetSerializableFields(System.Object)
    name: GetSerializableFields
    href: Prowl.Runtime.RuntimeUtils.html#Prowl_Runtime_RuntimeUtils_GetSerializableFields_System_Object_
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: Prowl.Runtime.RuntimeUtils.GetSerializableFields(System.Object)
    name: GetSerializableFields
    href: Prowl.Runtime.RuntimeUtils.html#Prowl_Runtime_RuntimeUtils_GetSerializableFields_System_Object_
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: Prowl.Runtime.RuntimeUtils
  commentId: T:Prowl.Runtime.RuntimeUtils
  parent: Prowl.Runtime
  href: Prowl.Runtime.RuntimeUtils.html
  name: RuntimeUtils
  nameWithType: RuntimeUtils
  fullName: Prowl.Runtime.RuntimeUtils
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: Prowl.Runtime
  commentId: N:Prowl.Runtime
  name: Prowl.Runtime
  nameWithType: Prowl.Runtime
  fullName: Prowl.Runtime
  spec.csharp:
  - uid: Prowl
    name: Prowl
  - name: .
  - uid: Prowl.Runtime
    name: Runtime
  spec.vb:
  - uid: Prowl
    name: Prowl
  - name: .
  - uid: Prowl.Runtime
    name: Runtime
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.string
  name: string
  nameWithType: string
  fullName: string
  nameWithType.vb: String
  fullName.vb: String
  name.vb: String
- uid: System.Type
  commentId: T:System.Type
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.type
  name: Type
  nameWithType: Type
  fullName: System.Type
