### YamlMime:ManagedReference
items:
- uid: Prowl.Editor.Projects.Settings.SerializerType
  commentId: T:Prowl.Editor.Projects.Settings.SerializerType
  id: SerializerType
  parent: Prowl.Editor.Projects.Settings
  children:
  - Prowl.Editor.Projects.Settings.SerializerType.Echo
  - Prowl.Editor.Projects.Settings.SerializerType.Standard
  langs:
  - csharp
  - vb
  name: SerializerType
  nameWithType: SerializerType
  fullName: Prowl.Editor.Projects.Settings.SerializerType
  type: Enum
  source:
    remote:
      path: Prowl.Editor/Projects/Settings/ProjectSettings.cs
      branch: main
      repo: https://github.com/ProwlEngine/Prowl.git
    id: SerializerType
    path: ../Prowl/Prowl.Editor/Projects/Settings/ProjectSettings.cs
    startLine: 19
  assemblies:
  - Prowl.Editor
  namespace: Prowl.Editor.Projects.Settings
  syntax:
    content: public enum SerializerType
    content.vb: Public Enum SerializerType
  extensionMethods:
  - System.Object.Prowl.Runtime.RuntimeUtils.GetSerializableFields
- uid: Prowl.Editor.Projects.Settings.SerializerType.Standard
  commentId: F:Prowl.Editor.Projects.Settings.SerializerType.Standard
  id: Standard
  parent: Prowl.Editor.Projects.Settings.SerializerType
  langs:
  - csharp
  - vb
  name: Standard
  nameWithType: SerializerType.Standard
  fullName: Prowl.Editor.Projects.Settings.SerializerType.Standard
  type: Field
  source:
    remote:
      path: Prowl.Editor/Projects/Settings/ProjectSettings.cs
      branch: main
      repo: https://github.com/ProwlEngine/Prowl.git
    id: Standard
    path: ../Prowl/Prowl.Editor/Projects/Settings/ProjectSettings.cs
    startLine: 19
  assemblies:
  - Prowl.Editor
  namespace: Prowl.Editor.Projects.Settings
  syntax:
    content: Standard = 0
    return:
      type: Prowl.Editor.Projects.Settings.SerializerType
- uid: Prowl.Editor.Projects.Settings.SerializerType.Echo
  commentId: F:Prowl.Editor.Projects.Settings.SerializerType.Echo
  id: Echo
  parent: Prowl.Editor.Projects.Settings.SerializerType
  langs:
  - csharp
  - vb
  name: Echo
  nameWithType: SerializerType.Echo
  fullName: Prowl.Editor.Projects.Settings.SerializerType.Echo
  type: Field
  source:
    remote:
      path: Prowl.Editor/Projects/Settings/ProjectSettings.cs
      branch: main
      repo: https://github.com/ProwlEngine/Prowl.git
    id: Echo
    path: ../Prowl/Prowl.Editor/Projects/Settings/ProjectSettings.cs
    startLine: 19
  assemblies:
  - Prowl.Editor
  namespace: Prowl.Editor.Projects.Settings
  syntax:
    content: Echo = 1
    return:
      type: Prowl.Editor.Projects.Settings.SerializerType
references:
- uid: Prowl.Editor.Projects.Settings
  commentId: N:Prowl.Editor.Projects.Settings
  name: Prowl.Editor.Projects.Settings
  nameWithType: Prowl.Editor.Projects.Settings
  fullName: Prowl.Editor.Projects.Settings
  spec.csharp:
  - uid: Prowl
    name: Prowl
  - name: .
  - uid: Prowl.Editor
    name: Editor
  - name: .
  - uid: Prowl.Editor.Projects
    name: Projects
  - name: .
  - uid: Prowl.Editor.Projects.Settings
    name: Settings
  spec.vb:
  - uid: Prowl
    name: Prowl
  - name: .
  - uid: Prowl.Editor
    name: Editor
  - name: .
  - uid: Prowl.Editor.Projects
    name: Projects
  - name: .
  - uid: Prowl.Editor.Projects.Settings
    name: Settings
- uid: System.Object.Prowl.Runtime.RuntimeUtils.GetSerializableFields
  commentId: M:Prowl.Runtime.RuntimeUtils.GetSerializableFields(System.Object)
  parent: Prowl.Runtime.RuntimeUtils
  definition: Prowl.Runtime.RuntimeUtils.GetSerializableFields(System.Object)
  href: Prowl.Runtime.RuntimeUtils.html#Prowl_Runtime_RuntimeUtils_GetSerializableFields_System_Object_
  name: GetSerializableFields(object)
  nameWithType: RuntimeUtils.GetSerializableFields(object)
  fullName: Prowl.Runtime.RuntimeUtils.GetSerializableFields(object)
  nameWithType.vb: RuntimeUtils.GetSerializableFields(Object)
  fullName.vb: Prowl.Runtime.RuntimeUtils.GetSerializableFields(Object)
  name.vb: GetSerializableFields(Object)
  spec.csharp:
  - uid: Prowl.Runtime.RuntimeUtils.GetSerializableFields(System.Object)
    name: GetSerializableFields
    href: Prowl.Runtime.RuntimeUtils.html#Prowl_Runtime_RuntimeUtils_GetSerializableFields_System_Object_
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: Prowl.Runtime.RuntimeUtils.GetSerializableFields(System.Object)
    name: GetSerializableFields
    href: Prowl.Runtime.RuntimeUtils.html#Prowl_Runtime_RuntimeUtils_GetSerializableFields_System_Object_
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: Prowl.Runtime.RuntimeUtils.GetSerializableFields(System.Object)
  commentId: M:Prowl.Runtime.RuntimeUtils.GetSerializableFields(System.Object)
  isExternal: true
  href: Prowl.Runtime.RuntimeUtils.html#Prowl_Runtime_RuntimeUtils_GetSerializableFields_System_Object_
  name: GetSerializableFields(object)
  nameWithType: RuntimeUtils.GetSerializableFields(object)
  fullName: Prowl.Runtime.RuntimeUtils.GetSerializableFields(object)
  nameWithType.vb: RuntimeUtils.GetSerializableFields(Object)
  fullName.vb: Prowl.Runtime.RuntimeUtils.GetSerializableFields(Object)
  name.vb: GetSerializableFields(Object)
  spec.csharp:
  - uid: Prowl.Runtime.RuntimeUtils.GetSerializableFields(System.Object)
    name: GetSerializableFields
    href: Prowl.Runtime.RuntimeUtils.html#Prowl_Runtime_RuntimeUtils_GetSerializableFields_System_Object_
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: Prowl.Runtime.RuntimeUtils.GetSerializableFields(System.Object)
    name: GetSerializableFields
    href: Prowl.Runtime.RuntimeUtils.html#Prowl_Runtime_RuntimeUtils_GetSerializableFields_System_Object_
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: Prowl.Runtime.RuntimeUtils
  commentId: T:Prowl.Runtime.RuntimeUtils
  parent: Prowl.Runtime
  href: Prowl.Runtime.RuntimeUtils.html
  name: RuntimeUtils
  nameWithType: RuntimeUtils
  fullName: Prowl.Runtime.RuntimeUtils
- uid: Prowl.Runtime
  commentId: N:Prowl.Runtime
  name: Prowl.Runtime
  nameWithType: Prowl.Runtime
  fullName: Prowl.Runtime
  spec.csharp:
  - uid: Prowl
    name: Prowl
  - name: .
  - uid: Prowl.Runtime
    name: Runtime
  spec.vb:
  - uid: Prowl
    name: Prowl
  - name: .
  - uid: Prowl.Runtime
    name: Runtime
- uid: Prowl.Editor.Projects.Settings.SerializerType
  commentId: T:Prowl.Editor.Projects.Settings.SerializerType
  parent: Prowl.Editor.Projects.Settings
  href: Prowl.Editor.Projects.Settings.SerializerType.html
  name: SerializerType
  nameWithType: SerializerType
  fullName: Prowl.Editor.Projects.Settings.SerializerType
