### YamlMime:ManagedReference
items:
- uid: Prowl.Editor.Projects.Settings.BuildTarget
  commentId: T:Prowl.Editor.Projects.Settings.BuildTarget
  id: BuildTarget
  parent: Prowl.Editor.Projects.Settings
  children:
  - Prowl.Editor.Projects.Settings.BuildTarget.Linux
  - Prowl.Editor.Projects.Settings.BuildTarget.MacOS
  - Prowl.Editor.Projects.Settings.BuildTarget.Windows
  langs:
  - csharp
  - vb
  name: BuildTarget
  nameWithType: BuildTarget
  fullName: Prowl.Editor.Projects.Settings.BuildTarget
  type: Enum
  source:
    remote:
      path: Prowl.Editor/Projects/Settings/BuildSettings.cs
      branch: main
      repo: https://github.com/ProwlEngine/Prowl.git
    id: BuildTarget
    path: ../Prowl/Prowl.Editor/Projects/Settings/BuildSettings.cs
    startLine: 16
  assemblies:
  - Prowl.Editor
  namespace: Prowl.Editor.Projects.Settings
  syntax:
    content: public enum BuildTarget
    content.vb: Public Enum BuildTarget
  extensionMethods:
  - System.Object.Prowl.Runtime.RuntimeUtils.GetSerializableFields
- uid: Prowl.Editor.Projects.Settings.BuildTarget.Windows
  commentId: F:Prowl.Editor.Projects.Settings.BuildTarget.Windows
  id: Windows
  parent: Prowl.Editor.Projects.Settings.BuildTarget
  langs:
  - csharp
  - vb
  name: Windows
  nameWithType: BuildTarget.Windows
  fullName: Prowl.Editor.Projects.Settings.BuildTarget.Windows
  type: Field
  source:
    remote:
      path: Prowl.Editor/Projects/Settings/BuildSettings.cs
      branch: main
      repo: https://github.com/ProwlEngine/Prowl.git
    id: Windows
    path: ../Prowl/Prowl.Editor/Projects/Settings/BuildSettings.cs
    startLine: 16
  assemblies:
  - Prowl.Editor
  namespace: Prowl.Editor.Projects.Settings
  syntax:
    content: Windows = 0
    return:
      type: Prowl.Editor.Projects.Settings.BuildTarget
- uid: Prowl.Editor.Projects.Settings.BuildTarget.Linux
  commentId: F:Prowl.Editor.Projects.Settings.BuildTarget.Linux
  id: Linux
  parent: Prowl.Editor.Projects.Settings.BuildTarget
  langs:
  - csharp
  - vb
  name: Linux
  nameWithType: BuildTarget.Linux
  fullName: Prowl.Editor.Projects.Settings.BuildTarget.Linux
  type: Field
  source:
    remote:
      path: Prowl.Editor/Projects/Settings/BuildSettings.cs
      branch: main
      repo: https://github.com/ProwlEngine/Prowl.git
    id: Linux
    path: ../Prowl/Prowl.Editor/Projects/Settings/BuildSettings.cs
    startLine: 16
  assemblies:
  - Prowl.Editor
  namespace: Prowl.Editor.Projects.Settings
  syntax:
    content: Linux = 1
    return:
      type: Prowl.Editor.Projects.Settings.BuildTarget
- uid: Prowl.Editor.Projects.Settings.BuildTarget.MacOS
  commentId: F:Prowl.Editor.Projects.Settings.BuildTarget.MacOS
  id: MacOS
  parent: Prowl.Editor.Projects.Settings.BuildTarget
  langs:
  - csharp
  - vb
  name: MacOS
  nameWithType: BuildTarget.MacOS
  fullName: Prowl.Editor.Projects.Settings.BuildTarget.MacOS
  type: Field
  source:
    remote:
      path: Prowl.Editor/Projects/Settings/BuildSettings.cs
      branch: main
      repo: https://github.com/ProwlEngine/Prowl.git
    id: MacOS
    path: ../Prowl/Prowl.Editor/Projects/Settings/BuildSettings.cs
    startLine: 16
  assemblies:
  - Prowl.Editor
  namespace: Prowl.Editor.Projects.Settings
  syntax:
    content: MacOS = 2
    return:
      type: Prowl.Editor.Projects.Settings.BuildTarget
references:
- uid: Prowl.Editor.Projects.Settings
  commentId: N:Prowl.Editor.Projects.Settings
  name: Prowl.Editor.Projects.Settings
  nameWithType: Prowl.Editor.Projects.Settings
  fullName: Prowl.Editor.Projects.Settings
  spec.csharp:
  - uid: Prowl
    name: Prowl
  - name: .
  - uid: Prowl.Editor
    name: Editor
  - name: .
  - uid: Prowl.Editor.Projects
    name: Projects
  - name: .
  - uid: Prowl.Editor.Projects.Settings
    name: Settings
  spec.vb:
  - uid: Prowl
    name: Prowl
  - name: .
  - uid: Prowl.Editor
    name: Editor
  - name: .
  - uid: Prowl.Editor.Projects
    name: Projects
  - name: .
  - uid: Prowl.Editor.Projects.Settings
    name: Settings
- uid: System.Object.Prowl.Runtime.RuntimeUtils.GetSerializableFields
  commentId: M:Prowl.Runtime.RuntimeUtils.GetSerializableFields(System.Object)
  parent: Prowl.Runtime.RuntimeUtils
  definition: Prowl.Runtime.RuntimeUtils.GetSerializableFields(System.Object)
  href: Prowl.Runtime.RuntimeUtils.html#Prowl_Runtime_RuntimeUtils_GetSerializableFields_System_Object_
  name: GetSerializableFields(object)
  nameWithType: RuntimeUtils.GetSerializableFields(object)
  fullName: Prowl.Runtime.RuntimeUtils.GetSerializableFields(object)
  nameWithType.vb: RuntimeUtils.GetSerializableFields(Object)
  fullName.vb: Prowl.Runtime.RuntimeUtils.GetSerializableFields(Object)
  name.vb: GetSerializableFields(Object)
  spec.csharp:
  - uid: Prowl.Runtime.RuntimeUtils.GetSerializableFields(System.Object)
    name: GetSerializableFields
    href: Prowl.Runtime.RuntimeUtils.html#Prowl_Runtime_RuntimeUtils_GetSerializableFields_System_Object_
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: Prowl.Runtime.RuntimeUtils.GetSerializableFields(System.Object)
    name: GetSerializableFields
    href: Prowl.Runtime.RuntimeUtils.html#Prowl_Runtime_RuntimeUtils_GetSerializableFields_System_Object_
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: Prowl.Runtime.RuntimeUtils.GetSerializableFields(System.Object)
  commentId: M:Prowl.Runtime.RuntimeUtils.GetSerializableFields(System.Object)
  isExternal: true
  href: Prowl.Runtime.RuntimeUtils.html#Prowl_Runtime_RuntimeUtils_GetSerializableFields_System_Object_
  name: GetSerializableFields(object)
  nameWithType: RuntimeUtils.GetSerializableFields(object)
  fullName: Prowl.Runtime.RuntimeUtils.GetSerializableFields(object)
  nameWithType.vb: RuntimeUtils.GetSerializableFields(Object)
  fullName.vb: Prowl.Runtime.RuntimeUtils.GetSerializableFields(Object)
  name.vb: GetSerializableFields(Object)
  spec.csharp:
  - uid: Prowl.Runtime.RuntimeUtils.GetSerializableFields(System.Object)
    name: GetSerializableFields
    href: Prowl.Runtime.RuntimeUtils.html#Prowl_Runtime_RuntimeUtils_GetSerializableFields_System_Object_
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: Prowl.Runtime.RuntimeUtils.GetSerializableFields(System.Object)
    name: GetSerializableFields
    href: Prowl.Runtime.RuntimeUtils.html#Prowl_Runtime_RuntimeUtils_GetSerializableFields_System_Object_
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: Prowl.Runtime.RuntimeUtils
  commentId: T:Prowl.Runtime.RuntimeUtils
  parent: Prowl.Runtime
  href: Prowl.Runtime.RuntimeUtils.html
  name: RuntimeUtils
  nameWithType: RuntimeUtils
  fullName: Prowl.Runtime.RuntimeUtils
- uid: Prowl.Runtime
  commentId: N:Prowl.Runtime
  name: Prowl.Runtime
  nameWithType: Prowl.Runtime
  fullName: Prowl.Runtime
  spec.csharp:
  - uid: Prowl
    name: Prowl
  - name: .
  - uid: Prowl.Runtime
    name: Runtime
  spec.vb:
  - uid: Prowl
    name: Prowl
  - name: .
  - uid: Prowl.Runtime
    name: Runtime
- uid: Prowl.Editor.Projects.Settings.BuildTarget
  commentId: T:Prowl.Editor.Projects.Settings.BuildTarget
  parent: Prowl.Editor.Projects.Settings
  href: Prowl.Editor.Projects.Settings.BuildTarget.html
  name: BuildTarget
  nameWithType: BuildTarget
  fullName: Prowl.Editor.Projects.Settings.BuildTarget
